name: Build & Publish Debug/Release APK

on:
  push:
    branches:
      - main
      - build-apk-in-gh-actions
    tags:
      - '*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        if: github.ref_type == 'branch'
        run: ./gradlew assembleDebug

      - name: Build Release APK
        if: github.ref_type == 'tag'
        run: ./gradlew assembleRelease

      - name: Set APK path
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "APK_PATH=app/build/outputs/apk/release/app-release.apk" >> $GITHUB_ENV
          else
            echo "APK_PATH=app/build/outputs/apk/debug/app-debug.apk" >> $GITHUB_ENV
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.APK_PATH }}

      - name: Publish APK
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.APK_PATH }}